
cmake -S . \
  -B ./.ntt/cmake/build \
  -DCMAKE_TOOLCHAIN_FILE:FILEPATH=$VCPKG_TOOLCHAIN_FILE \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
  -DCMAKE_INSTALL_PREFIX=$HOME/bin \
  -DCMAKE_COLOR_DIAGNOSTICS:BOOL=ON \
  -DNTT_TEST:BOOL=ON;